name: demo
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  permission_handler: ^8.3.0
  url_launcher: ^5.4.0
  firebase_core: ^1.12.0
  firebase_auth: ^3.3.6
  cloud_firestore: ^3.1.7
  path_provider: ^2.0.8
  firebase_storage: ^10.2.6
  fluttertoast: ^8.0.8
  provider: ^6.0.2
  qr_code_scanner: ^0.6.1
  camera:
  path:
  video_player: ^2.1.4
  stacked_services: ^0.8.6
  get_it: ^7.1.3
  stacked: ^2.1.7
  cached_network_image: ^3.0.0

  flutter_lints: ^1.0.4

flutter:
  assets:
    - Pics/logo.PNG
    - Pics/SM.png
    - Pics/image0.png
    - Pics/tok.png
  uses-material-design: true

